[mysql]
host = "127.0.0.1"
name = "chat"
password = "123456"
port = 3306
tablePrefix = ""
user = "root"

[msgChannelType]
channelType = "gochannel"
kafkaHosts = "kafka:9092"
kafkaTopic = "go-chat-message"
